export const config = {
  port: parseInt(process.env.PORT || "3000", 10),
  databaseUrl: process.env.OUTLETS_SERVICE_DATABASE_URL || process.env.DATABASE_URL || "",
  apiKey: process.env.OUTLETS_SERVICE_API_KEY || "",
  chatServiceUrl: process.env.CHAT_SERVICE_URL || "",
  chatServiceApiKey: process.env.CHAT_SERVICE_API_KEY || "",
  googleServiceUrl: process.env.GOOGLE_SERVICE_URL || "",
  googleServiceApiKey: process.env.GOOGLE_SERVICE_API_KEY || "",
  brandServiceUrl: process.env.BRAND_SERVICE_URL || "",
  brandServiceApiKey: process.env.BRAND_SERVICE_API_KEY || "",
  campaignServiceUrl: process.env.CAMPAIGN_SERVICE_URL || "",
  campaignServiceApiKey: process.env.CAMPAIGN_SERVICE_API_KEY || "",
  featuresServiceUrl: process.env.FEATURES_SERVICE_URL || "",
  featuresServiceApiKey: process.env.FEATURES_SERVICE_API_KEY || "",
  workflowServiceUrl: process.env.WORKFLOW_SERVICE_URL || "",
  workflowServiceApiKey: process.env.WORKFLOW_SERVICE_API_KEY || "",
  runsServiceUrl: process.env.RUNS_SERVICE_URL || "",
  runsServiceApiKey: process.env.RUNS_SERVICE_API_KEY || "",
};
